name: Pull Request

on: pull_request

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - run: npm run lint

  auto-merge:
    runs-on: ubuntu-latest
    needs: [integration]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: gh pr merge '${{ github.event.pull_request.number }}' --auto --merge
        if: github.actor == 'dependabot[bot]'
        env:
          GH_TOKEN: ${{ github.token }}
